// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/pages/tvseries/tvseries_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities/tvseries/tvseries.dart' as _i10;
import 'package:ditonton/domain/entities/tvseries/tvseries_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/tvseries/get_tvseries_detail.dart'
    as _i2;
import 'package:ditonton/domain/usecases/tvseries/get_tvseries_recommendation.dart'
    as _i3;
import 'package:ditonton/domain/usecases/tvseries/get_watchlist_tvseries_status.dart'
    as _i4;
import 'package:ditonton/domain/usecases/tvseries/remove_watchlist_tvseries.dart'
    as _i6;
import 'package:ditonton/domain/usecases/tvseries/save_watchlist_tvseries.dart'
    as _i5;
import 'package:ditonton/presentation/provider/tvseries/tvseries_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTVSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTVSeriesDetail {
  _FakeGetTVSeriesDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTVSeriesRecommendation_1 extends _i1.SmartFake
    implements _i3.GetTVSeriesRecommendation {
  _FakeGetTVSeriesRecommendation_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListTVSeriesStatus_2 extends _i1.SmartFake
    implements _i4.GetWatchListTVSeriesStatus {
  _FakeGetWatchListTVSeriesStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchListTVSeries_3 extends _i1.SmartFake
    implements _i5.SaveWatchListTVSeries {
  _FakeSaveWatchListTVSeries_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchListTVSeries_4 extends _i1.SmartFake
    implements _i6.RemoveWatchListTVSeries {
  _FakeRemoveWatchListTVSeries_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTVSeriesDetail_5 extends _i1.SmartFake
    implements _i7.TVSeriesDetail {
  _FakeTVSeriesDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TVSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDetailNotifier extends _i1.Mock
    implements _i8.TVSeriesDetailNotifier {
  MockTVSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVSeriesDetail get getTVSeriesDetail => (super.noSuchMethod(
        Invocation.getter(#getTVSeriesDetail),
        returnValue: _FakeGetTVSeriesDetail_0(
          this,
          Invocation.getter(#getTVSeriesDetail),
        ),
      ) as _i2.GetTVSeriesDetail);

  @override
  _i3.GetTVSeriesRecommendation get getTVSeriesRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getTVSeriesRecommendations),
        returnValue: _FakeGetTVSeriesRecommendation_1(
          this,
          Invocation.getter(#getTVSeriesRecommendations),
        ),
      ) as _i3.GetTVSeriesRecommendation);

  @override
  _i4.GetWatchListTVSeriesStatus get getWatchListTvStatus =>
      (super.noSuchMethod(
        Invocation.getter(#getWatchListTvStatus),
        returnValue: _FakeGetWatchListTVSeriesStatus_2(
          this,
          Invocation.getter(#getWatchListTvStatus),
        ),
      ) as _i4.GetWatchListTVSeriesStatus);

  @override
  _i5.SaveWatchListTVSeries get saveWatchListTv => (super.noSuchMethod(
        Invocation.getter(#saveWatchListTv),
        returnValue: _FakeSaveWatchListTVSeries_3(
          this,
          Invocation.getter(#saveWatchListTv),
        ),
      ) as _i5.SaveWatchListTVSeries);

  @override
  _i6.RemoveWatchListTVSeries get removeWatchListTv => (super.noSuchMethod(
        Invocation.getter(#removeWatchListTv),
        returnValue: _FakeRemoveWatchListTVSeries_4(
          this,
          Invocation.getter(#removeWatchListTv),
        ),
      ) as _i6.RemoveWatchListTVSeries);

  @override
  _i7.TVSeriesDetail get tv => (super.noSuchMethod(
        Invocation.getter(#tv),
        returnValue: _FakeTVSeriesDetail_5(
          this,
          Invocation.getter(#tv),
        ),
      ) as _i7.TVSeriesDetail);

  @override
  _i9.RequestState get tvState => (super.noSuchMethod(
        Invocation.getter(#tvState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);

  @override
  List<_i10.TVSeries> get tvRecommendations => (super.noSuchMethod(
        Invocation.getter(#tvRecommendations),
        returnValue: <_i10.TVSeries>[],
      ) as List<_i10.TVSeries>);

  @override
  _i9.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);

  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#watchlistMessage),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> fetchTvDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvDetail,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> addWatchlist(_i7.TVSeriesDetail? tv) => (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tv],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> removeFromWatchlist(_i7.TVSeriesDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tv],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
