// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeFQoSZelgd7FW_UrYafA2hN3Fh4xghjA',
    appId: '1:181961208142:web:77298360201dbcd2a0ee1f',
    messagingSenderId: '181961208142',
    projectId: 'fditonton',
    authDomain: 'fditonton.firebaseapp.com',
    storageBucket: 'fditonton.appspot.com',
    measurementId: 'G-NGNC6M0VY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo7A4Q2ZzoK7jdQkkDgi-JN7ggJJiHgZk',
    appId: '1:181961208142:android:b1ff5fa3a08d5513a0ee1f',
    messagingSenderId: '181961208142',
    projectId: 'fditonton',
    storageBucket: 'fditonton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnSYAiJbFgimdSjoVpsWd0zzeOIZfAdwA',
    appId: '1:181961208142:ios:96be600d7bf9ea66a0ee1f',
    messagingSenderId: '181961208142',
    projectId: 'fditonton',
    storageBucket: 'fditonton.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
